# Generated by Django 5.1.4 on 2025-04-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
