# Generated by Django 5.1.4 on 2025-08-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, default='../media/default/noimage.png', null=True, upload_to='post_images/'),
        ),
    ]
